apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.globalName }}-ui-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.globalName }}-ui
  servers:
  - port:
      number: 80
      name: http-port
      protocol: HTTP
    hosts:
    - {{ .Values.ingress_host }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-port
      protocol: HTTPS
    hosts:
    - {{ .Values.ingress_host }}
    tls:
      mode: {{ .Values.gateway_tls_mode }}
      serverCertificate: /etc/certs/servercert.pem
      privateKey: /etc/certs/privatekey.pem